#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Eiki Nakayama <qwertyuiop1103566@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only
import sys
・・・

import sys
   
ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
